name: Tests Plone 6
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        plone-version: ['6.0']
        python-version: ['3.7', '3.8', '3.9']

    steps:
      # git checkout
      - uses: actions/checkout@v2

      # python setup
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      # python cache
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # pip install
      - name: pip install
        run: pip install -r requirements-60.txt -r requirements-docs.txt

      # buildout
      - name: buildout
        run: buildout -t 10 -c plone-${{ matrix.plone-version }}.x.cfg code-analysis:return-status-codes=True
        env:
          CI: true

      # code analysis
      - name: code analysis
        run: bin/code-analysis

      # test
      - name: test
        run: bin/test

      # Commented out a few actions that should not currently be run on Plone 6.
      # Kept a note here, so we do not forget about them when we drop Plone 5 support.
      # build sphinx
      # test no uncommited changes
      # test sphinx warnings
